---
title: "BeginAnalysis"
author: "Eamon"
date: "2024-12-18"
output: html_document
---
# Initialisation
## Set Up
### Load Libraries
```{r}
library(tidyverse)
library(corrplot) # For correlation plots
library(FactoMineR) # For PCA
library(factoextra) # For PCA plots
library(vegan) # For CCA
```

### 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Clear environment
```{r}
rm(list = ls())
```


### Specify the FilePath and Read CSV
```{r}
path <- "/Users/eamon/Desktop/MathToolsProject/R_Project/MathematicalTools/lizard.csv"

# Read a CSV file
data <- read.csv(path)

# View the first few rows of the data
data
```

## Cleaning
### Change Variables Types
```{r}
# Check the type of each column
sapply(data, class)

# Convert SD.Female.adult.weight..g. to numeric
data$SD.Female.adult.weight..g. <- as.numeric(data$SD.Female.adult.weight..g.)

# Convert categorical columns to factors
data$Species <- as.factor(data$Species)
data$Genus <- as.factor(data$Genus)
data$Family<- as.factor(data$Family)
data$Mode.of.reproduction <- as.factor(data$Mode.of.reproduction)
data$Foraging.Mode <- as.factor(data$Foraging.Mode)
data$Distribution <- as.factor(data$Distribution)
data$Prefered.Habitat.Type <- as.factor(data$Prefered.Habitat.Type)
```

### Check for and Remove Duplicates
```{r}
# Check for Duplicates
duplicates <- data[duplicated(data), ]
print("Duplicate Rows:")
print(duplicates)

# Remove duplicates
data <- data[!duplicated(data), ]
```

